### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/birthstone#4]
## Google Fonts Latin Plus coverage

- [x] Design all the glyphs required in the [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [x] Create all the comb marks as mentioned below
- [x] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and matching the style of the typeface design.
- [x] Adjust the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke, I think most of this has been solved already, but I'm creating the issue anyway to track the development. Please check the boxes.

**Comment by vv-monsalve** [comment]
The design issues related to Birthstone Bounce I think should be posted in a separate repository, now that we are going to publish them as sibling families.
@davelab6 could you please create the new repository for Birthstone Bounce with the template created by Simon? :)

**Comment by davelab6** [comment]
Done @ https://github.com/googlefonts/birthstone-bounce

**Comment by vv-monsalve** [comment]
Hi @crystaltype, these are the images of the review we made on Birthstone.
Please remember to inspect this for all of the projects. 

@RobLeuschke, please also keep these fixes in mind when working on all the other Batch 2 projects.

- [ ] Macron width and probably even slope as Rob said in our meeting.
<img width="413" alt="Screen Shot 2021-07-27 at 9 18 50" src="https://user-images.githubusercontent.com/48698976/127251895-00cefd90-d8d3-425b-9327-4ce947b06bbd.png">

- [ ] Marks in `ae` should go centered for the entire glyph
<img width="646" alt="Screen Shot 2021-07-27 at 9 27 33" src="https://user-images.githubusercontent.com/48698976/127251976-17715f06-c002-4032-bcc6-c05b12f8d394.png">

- [ ] Double marks as `doublegrave` and `hungarhumlaut` subtle fixes in slope and distance between the outlines to avoid extra white space, ensuring it is perceived as an unity
<img width="386" alt="Screen Shot 2021-07-27 at 9 29 41" src="https://user-images.githubusercontent.com/48698976/127252052-5487dbcc-901b-49fe-b646-393661fc3ac4.png">

- [ ] Avoid/solve colliding among shapes
<img width="600" alt="Screen Shot 2021-07-27 at 9 29 58" src="https://user-images.githubusercontent.com/48698976/127252212-792ce326-dfd1-4226-96ca-0d796580bb35.png">

- [ ] Fix spacing to ensure smooth connections between letters (see above and below images)
<img width="1178" alt="Screen Shot 2021-07-27 at 9 31 20" src="https://user-images.githubusercontent.com/48698976/127252398-eab4a03c-8284-49cd-bd39-f55f64d4c8f6.png">

- [ ] Distance between marks
<img width="392" alt="Screen Shot 2021-07-27 at 9 33 38" src="https://user-images.githubusercontent.com/48698976/127252539-c9ee8a46-9884-4608-9327-2ab4beba2255.png">

- [ ] Ensuring anchor position relative to main counter shape
<img width="870" alt="Screen Shot 2021-07-27 at 9 34 34" src="https://user-images.githubusercontent.com/48698976/127252581-59481cae-6ddb-4d72-8ed7-2f053cb33d93.png">

- [ ] Ensure compound glyphs are updated
<img width="652" alt="Screen Shot 2021-07-27 at 9 37 46" src="https://user-images.githubusercontent.com/48698976/127252621-17126ea0-5b61-4fab-b821-4fe6915aebff.png">

- [ ] Ensure using the right base letters in digraphs
<img width="414" alt="Screen Shot 2021-07-27 at 9 41 19" src="https://user-images.githubusercontent.com/48698976/127252776-79bebb5a-2ab0-4f5a-b5d1-e508ce68fb61.png">

**Comment by vv-monsalve** [comment]
@RobLeuschke, After Nhung finish the above fixes, we'll update the file in DropBox so that you could fix the `Germandbls`

<img width="725" alt="Screen Shot 2021-07-27 at 9 42 21" src="https://user-images.githubusercontent.com/48698976/127252993-d4080de3-c7ac-4dad-addf-923628505e70.png">

**Comment by RobLeuschke** [comment]
I await your instructions to proceed with correcting the Germandbl.

**Comment by vv-monsalve** [comment]
@RobLeuschke The file `BirthstonePro.glyphs` with the latest adjustments is now in your DropBox. Please use it to include the `Germandbls` fixes. Thanks

**Comment by RobLeuschke** [comment]
The germandbls have been revised. I also found a few things needing attention (For ex. the four_superior was too high vertically).

**Comment by RobLeuschke** [comment]
I also fixed the connections. When the extrema feature is applied to such tightly designed areas, the shapes distort ever so slightly. The lowercase r needed some tweaks to connect to other lc glyphs.

**Comment by vv-monsalve** [comment]
> There are a number of such ligatures that were not programmed— that has been corrected and I have created a clig feature.

Hi @RobLeuschke, thanks for the feature it is working. I renamed it to the most common `calt` for this type of use.
